# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Park.destroy_all
animal_kingdom = Park.create!(name: "Animal Kingdom")
blizzard_beach = Park.create!(name: "Blizzard Beach")
epcot = Park.create!(name: "Epcot")
hollywood_studios = Park.create!(name: "Hollywood Studios")
magic_kingdom = Park.create!(name: "Magic Kingdom")
typhoon_lagoon = Park.create!(name: "Typhoon Lagoon")

Rate.destroy_all
rate_one = Rate.create!(rating_value: "1 - worst")
rate_two = Rate.create!(rating_value: "2 - very poor")
rate_three = Rate.create!(rating_value: "3 - way below average")
rate_four = Rate.create!(rating_value: "4 - below average")
rate_five = Rate.create!(rating_value: "5 - average")
rate_six = Rate.create!(rating_value: "6 - above average")
rate_seven = Rate.create!(rating_value: "7 - way above average")
rate_eight = Rate.create!(rating_value: "8 - good")
rate_nine = Rate.create!(rating_value: "9 - great")
rate_ten = Rate.create!(rating_value: "10 - best")

Area.destroy_all
adventureland = Area.create!(name: "Adventureland")
fantasyland = Area.create!(name: "Fantasyland")
frontierland = Area.create!(name: "Frontierland")
liberty_square = Area.create!(name: "Liberty Square")
main_street_usa = Area.create!(name: "Main Street USA")
tomorrowland = Area.create!(name: "Tomorrowland")
future_world_east = Area.create!(name: "Future World East")
future_world_west = Area.create!(name: "Future World West")
world_showcase_mexico = Area.create!(name: "World Showcase Mexico")
world_showcase_norway = Area.create!(name: "World Showcase Norway")
world_showcase_china = Area.create!(name: "World Showcase China")
world_showcase_germany = Area.create!(name: "World Showcase Germany")
world_showcase_italy = Area.create!(name: "World Showcase Italy")
world_showcase_the_american_adventure = Area.create!(name: "World Showcase The American Adventure")
world_showcase_japan = Area.create!(name: "World Showcase Japan")
world_showcase_morocco = Area.create!(name: "World Showcase Morocco")
world_showcase_france = Area.create!(name: "World Showcase France")
world_showcase_united_kingdom = Area.create!(name: "World Showcase United Kingdom")
world_showcase_canada = Area.create!(name: "World Showcase Canada")
hollywood_boulevard = Area.create!(name: "Hollywood Boulevard")
echo_lake = Area.create!(name: "Echo Lake")
muppets_courtyard = Area.create!(name: "Muppets Courtyard")
commissary_lane = Area.create!(name: "Commissary Lane")
pixar_place = Area.create!(name: "Pixar Place")
animation_courtyard = Area.create!(name: "Animation Courtyard")
sunset_boulevard = Area.create!(name: "Sunset Boulevard")
oasis = Area.create!(name: "Oasis")
discovery_island = Area.create!(name: "Discovery Island")
pandora_world_of_avatar = Area.create!(name: "Pandora World of Avatar")
africa = Area.create!(name: "Africa")
asia = Area.create!(name: "Asia")
dinoland_usa = Area.create!(name: "Dinoland USA")
blizzard_beach_area = Area.create!(name: "Blizzard Beach Area")
typhoon_lagoon_area = Area.create!(name: "Typhoon Lagoon Area")
